[required]

acquisition      = 'stabilty' # or 'spectrum'
keithley_model   = 6487
save_name        = 'test'

[optional]

overwrite        = False
num_samples      = 100
sipm_bias        = 53
monochrom_angle  = 4.3
interval_mins    = 5.0
